[2024-10-03 08:59:31,627] p7229 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:134} INFO - I will get links for 1 cities
[2024-10-03 08:59:31,628] p7229 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:153} INFO - sleeping for 24.72 seconds
[2024-10-03 08:59:56,350] p7229 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:156} INFO - get links for city: Воронеж
[2024-10-03 09:00:00,875] p7229 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-10-03 09:00:06,594] p7229 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:58} INFO - sleep for 17.28
[2024-10-03 09:00:38,041] p7326 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:134} INFO - I will get links for 1 cities
[2024-10-03 09:00:38,042] p7326 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:153} INFO - sleeping for 32.19 seconds
[2024-10-03 09:01:10,235] p7326 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:156} INFO - get links for city: Воронеж
[2024-10-03 09:01:13,034] p7326 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-10-03 09:01:19,277] p7326 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:58} INFO - sleep for 15.89
[2024-10-03 09:01:35,197] p7326 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:106} INFO - driver stopped
[2024-10-03 09:01:35,489] p7326 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/urllib3/connectionpool.py:780} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1068dc550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/192d8eb139cf8e8d4d8054cfcc57ff9c/window
[2024-10-03 09:01:35,490] p7326 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/urllib3/connectionpool.py:780} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1068dc880>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/192d8eb139cf8e8d4d8054cfcc57ff9c/window
[2024-10-03 09:01:35,491] p7326 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/urllib3/connectionpool.py:780} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1068dc850>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/192d8eb139cf8e8d4d8054cfcc57ff9c/window
[2024-10-03 09:01:35,492] p7326 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:161} INFO - Error in get links for city: Воронеж, error: HTTPConnectionPool(host='localhost', port=49790): Max retries exceeded with url: /session/192d8eb139cf8e8d4d8054cfcc57ff9c/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1068dca60>: Failed to establish a new connection: [Errno 61] Connection refused'))
