[2024-05-06 11:06:18,238] p3148 {/Users/anyarulina/parser/pipeline_review.py:132} INFO - start pipeline for None at 2024-05-06 11:06:18.238218
[2024-05-06 11:06:18,238] p3148 {/Users/anyarulina/parser/pipeline_review.py:136} INFO - 631 cities in input
[2024-05-06 11:06:18,239] p3148 {/Users/anyarulina/parser/pipeline_review.py:91} INFO - start get info for None at 2024-05-06 11:06:18.238993
[2024-05-06 11:06:18,239] p3148 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  0
[2024-05-06 11:06:18,239] p3148 {/Users/anyarulina/parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/parser/pipeline_review.py", line 154, in <module>
    funcs = get_all_reviews(cities, bank_name, check_existing=True)
  File "/Users/anyarulina/parser/pipeline_review.py", line 94, in get_all_reviews
    cities_dict = get_not_handled_reviews(bank_name)
  File "/Users/anyarulina/parser/pipeline_review.py", line 38, in get_not_handled_reviews
    only_links_files = [f for f in listdir(links_path) if isfile(join(links_path, f))]
FileNotFoundError: [Errno 2] No such file or directory: 'links/None/'
[2024-05-06 11:06:50,839] p3226 {/Users/anyarulina/parser/pipeline_review.py:132} INFO - start pipeline for sberbank at 2024-05-06 11:06:50.839435
[2024-05-06 11:06:50,839] p3226 {/Users/anyarulina/parser/pipeline_review.py:136} INFO - 631 cities in input
[2024-05-06 11:06:50,839] p3226 {/Users/anyarulina/parser/pipeline_review.py:91} INFO - start get info for sberbank at 2024-05-06 11:06:50.839826
[2024-05-06 11:06:50,860] p3226 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:06:50,891] p3226 {/Users/anyarulina/parser/pipeline_review.py:55} INFO - len existing_links  5727
[2024-05-06 11:06:50,900] p3226 {/Users/anyarulina/parser/pipeline_review.py:75} INFO - len not_handled_reviews  1409
[2024-05-06 11:06:50,900] p3226 {/Users/anyarulina/parser/pipeline_review.py:110} INFO - I will get reviews for 1409 banks
[2024-05-06 11:06:50,900] p3226 {/Users/anyarulina/parser/get_reviews.py:66} INFO - starting get reviews for Россошь city
[2024-05-06 11:06:50,900] p3226 {/Users/anyarulina/parser/get_reviews.py:82} INFO - I will handle 1 banks for city Россошь
[2024-05-06 11:06:50,900] p3226 {/Users/anyarulina/parser/get_reviews.py:83} INFO - links: ['https://yandex.ru/maps/org/sberbank/97017180197']
[2024-05-06 11:06:50,901] p3226 {/Users/anyarulina/parser/get_reviews.py:99} INFO - starting get reviews for id 97017180197
[2024-05-06 11:06:54,755] p3226 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-05-06 11:07:03,685] p3226 {/Users/anyarulina/parser/get_reviews.py:27} INFO - I finish parse.parse 
[2024-05-06 11:07:03,685] p3226 {/Users/anyarulina/parser/get_reviews.py:107} INFO - error 'dict' object has no attribute 'append'
[2024-05-06 11:07:03,685] p3226 {/Users/anyarulina/parser/get_reviews.py:108} INFO - 97017180197 not handled
[2024-05-06 11:07:03,686] p3226 {/Users/anyarulina/parser/get_reviews.py:115} INFO - 0 items left
[2024-05-06 11:07:03,686] p3226 {/Users/anyarulina/parser/get_reviews.py:118} INFO - where are no handled banks in city Россошь lentgh of 1: {'Россошь': '97017180197'}
[2024-05-06 11:07:03,686] p3226 {/Users/anyarulina/parser/get_reviews.py:66} INFO - starting get reviews for Омск city
[2024-05-06 11:07:03,687] p3226 {/Users/anyarulina/parser/get_reviews.py:82} INFO - I will handle 1 banks for city Омск
[2024-05-06 11:07:03,687] p3226 {/Users/anyarulina/parser/get_reviews.py:83} INFO - links: ['https://yandex.ru/maps/org/sberbank/90704224041']
[2024-05-06 11:07:03,687] p3226 {/Users/anyarulina/parser/get_reviews.py:99} INFO - starting get reviews for id 90704224041
[2024-05-06 11:07:07,358] p3226 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-05-06 11:07:16,414] p3226 {/Users/anyarulina/parser/get_reviews.py:27} INFO - I finish parse.parse 
[2024-05-06 11:07:16,414] p3226 {/Users/anyarulina/parser/get_reviews.py:107} INFO - error 'dict' object has no attribute 'append'
[2024-05-06 11:07:16,414] p3226 {/Users/anyarulina/parser/get_reviews.py:108} INFO - 90704224041 not handled
[2024-05-06 11:07:16,414] p3226 {/Users/anyarulina/parser/get_reviews.py:115} INFO - 0 items left
[2024-05-06 11:07:16,414] p3226 {/Users/anyarulina/parser/get_reviews.py:118} INFO - where are no handled banks in city Омск lentgh of 1: {'Омск': '90704224041'}
[2024-05-06 11:07:16,414] p3226 {/Users/anyarulina/parser/get_reviews.py:66} INFO - starting get reviews for Белово city
[2024-05-06 11:07:16,415] p3226 {/Users/anyarulina/parser/get_reviews.py:82} INFO - I will handle 1 banks for city Белово
[2024-05-06 11:07:16,415] p3226 {/Users/anyarulina/parser/get_reviews.py:83} INFO - links: ['https://yandex.ru/maps/org/sberbank/1005687823']
[2024-05-06 11:07:16,415] p3226 {/Users/anyarulina/parser/get_reviews.py:99} INFO - starting get reviews for id 1005687823
[2024-05-06 11:07:18,794] p3226 {/Users/anyarulina/parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/parser/pipeline_review.py", line 154, in <module>
    funcs = get_all_reviews(cities, bank_name, check_existing=True)
  File "/Users/anyarulina/parser/pipeline_review.py", line 113, in get_all_reviews
    get_cities_reviews(cities_dict, bank_name)
  File "/Users/anyarulina/parser/get_reviews.py", line 100, in get_cities_reviews
    parse_ans_save_reviews(yandex_bank_id, city_name, bank_name)
  File "/Users/anyarulina/parser/get_reviews.py", line 26, in parse_ans_save_reviews
    reviews = parser.parse(type_parse='reviews')
  File "/Users/anyarulina/parser/parser/utils.py", line 36, in parse
    page = self.__open_page()
  File "/Users/anyarulina/parser/parser/utils.py", line 21, in __open_page
    driver = undetected_chromedriver.Chrome(options=opts)
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/urllib/request.py", line 268, in urlretrieve
    block = fp.read(bs)
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/anyarulina/miniconda3/envs/main/lib/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
[2024-05-06 11:13:10,228] p3544 {/Users/anyarulina/parser/pipeline_review.py:132} INFO - start pipeline for sberbank at 2024-05-06 11:13:10.228007
[2024-05-06 11:13:10,228] p3544 {/Users/anyarulina/parser/pipeline_review.py:139} INFO - 1 cities in input
[2024-05-06 11:13:10,228] p3544 {/Users/anyarulina/parser/pipeline_review.py:91} INFO - start get info for sberbank at 2024-05-06 11:13:10.228190
[2024-05-06 11:13:10,246] p3544 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:13:10,274] p3544 {/Users/anyarulina/parser/pipeline_review.py:55} INFO - len existing_links  5727
[2024-05-06 11:13:10,283] p3544 {/Users/anyarulina/parser/pipeline_review.py:75} INFO - len not_handled_reviews  1409
[2024-05-06 11:13:10,283] p3544 {/Users/anyarulina/parser/pipeline_review.py:110} INFO - I will get reviews for 1409 banks
[2024-05-06 11:13:10,283] p3544 {/Users/anyarulina/parser/get_reviews.py:66} INFO - starting get reviews for Россошь city
[2024-05-06 11:13:10,284] p3544 {/Users/anyarulina/parser/get_reviews.py:82} INFO - I will handle 1 banks for city Россошь
[2024-05-06 11:13:10,284] p3544 {/Users/anyarulina/parser/get_reviews.py:83} INFO - links: ['https://yandex.ru/maps/org/sberbank/97017180197']
[2024-05-06 11:13:10,284] p3544 {/Users/anyarulina/parser/get_reviews.py:99} INFO - starting get reviews for id 97017180197
[2024-05-06 11:13:13,672] p3544 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-05-06 11:13:22,764] p3544 {/Users/anyarulina/parser/get_reviews.py:27} INFO - I finish parse.parse 
[2024-05-06 11:13:22,764] p3544 {/Users/anyarulina/parser/get_reviews.py:107} INFO - error 'dict' object has no attribute 'append'
[2024-05-06 11:13:22,764] p3544 {/Users/anyarulina/parser/get_reviews.py:108} INFO - 97017180197 not handled
[2024-05-06 11:13:22,765] p3544 {/Users/anyarulina/parser/get_reviews.py:115} INFO - 0 items left
[2024-05-06 11:13:22,765] p3544 {/Users/anyarulina/parser/get_reviews.py:118} INFO - where are no handled banks in city Россошь lentgh of 1: {'Россошь': '97017180197'}
[2024-05-06 11:13:22,765] p3544 {/Users/anyarulina/parser/get_reviews.py:66} INFO - starting get reviews for Омск city
[2024-05-06 11:13:22,765] p3544 {/Users/anyarulina/parser/get_reviews.py:82} INFO - I will handle 1 banks for city Омск
[2024-05-06 11:13:22,765] p3544 {/Users/anyarulina/parser/get_reviews.py:83} INFO - links: ['https://yandex.ru/maps/org/sberbank/90704224041']
[2024-05-06 11:13:22,765] p3544 {/Users/anyarulina/parser/get_reviews.py:99} INFO - starting get reviews for id 90704224041
[2024-05-06 11:14:53,437] p3653 {/Users/anyarulina/parser/pipeline_review.py:137} INFO - start pipeline for sberbank at 2024-05-06 11:14:53.437082
[2024-05-06 11:14:53,437] p3653 {/Users/anyarulina/parser/pipeline_review.py:144} INFO - 1 cities in input
[2024-05-06 11:14:53,437] p3653 {/Users/anyarulina/parser/pipeline_review.py:91} INFO - start get info for sberbank at 2024-05-06 11:14:53.437290
[2024-05-06 11:14:53,455] p3653 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:14:53,484] p3653 {/Users/anyarulina/parser/pipeline_review.py:55} INFO - len existing_links  5727
[2024-05-06 11:14:53,492] p3653 {/Users/anyarulina/parser/pipeline_review.py:75} INFO - len not_handled_reviews  1409
[2024-05-06 11:14:53,495] p3653 {/Users/anyarulina/parser/pipeline_review.py:115} INFO - I will get reviews for 1409 banks
[2024-05-06 11:14:53,495] p3653 {/Users/anyarulina/parser/pipeline_review.py:120} INFO - Got info for in 0:00:00.058208 seconds
[2024-05-06 11:14:53,495] p3653 {/Users/anyarulina/parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/parser/pipeline_review.py", line 165, in <module>
    for func in funcs:
TypeError: 'NoneType' object is not iterable
[2024-05-06 11:15:30,649] p3697 {/Users/anyarulina/parser/pipeline_review.py:140} INFO - start pipeline for sberbank at 2024-05-06 11:15:30.648986
[2024-05-06 11:15:30,649] p3697 {/Users/anyarulina/parser/pipeline_review.py:147} INFO - 1 cities in input
[2024-05-06 11:15:30,649] p3697 {/Users/anyarulina/parser/pipeline_review.py:91} INFO - start get info for sberbank at 2024-05-06 11:15:30.649188
[2024-05-06 11:15:30,666] p3697 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:15:30,695] p3697 {/Users/anyarulina/parser/pipeline_review.py:55} INFO - len existing_links  5727
[2024-05-06 11:15:30,703] p3697 {/Users/anyarulina/parser/pipeline_review.py:75} INFO - len not_handled_reviews  1409
[2024-05-06 11:15:30,703] p3697 {/Users/anyarulina/parser/pipeline_review.py:118} INFO - I will get reviews for 1 banks
[2024-05-06 11:15:30,703] p3697 {/Users/anyarulina/parser/pipeline_review.py:123} INFO - Got info for in 0:00:00.054653 seconds
[2024-05-06 11:15:30,703] p3697 {/Users/anyarulina/parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/parser/pipeline_review.py", line 168, in <module>
    for func in funcs:
TypeError: 'NoneType' object is not iterable
[2024-05-06 11:16:29,775] p3726 {/Users/anyarulina/parser/pipeline_review.py:141} INFO - start pipeline for sberbank at 2024-05-06 11:16:29.775013
[2024-05-06 11:16:29,775] p3726 {/Users/anyarulina/parser/pipeline_review.py:148} INFO - 1 cities in input
[2024-05-06 11:16:29,775] p3726 {/Users/anyarulina/parser/pipeline_review.py:91} INFO - start get info for sberbank at 2024-05-06 11:16:29.775217
[2024-05-06 11:16:29,792] p3726 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:16:29,820] p3726 {/Users/anyarulina/parser/pipeline_review.py:55} INFO - len existing_links  5727
[2024-05-06 11:16:29,829] p3726 {/Users/anyarulina/parser/pipeline_review.py:75} INFO - len not_handled_reviews  1409
[2024-05-06 11:16:29,829] p3726 {/Users/anyarulina/parser/pipeline_review.py:119} INFO - I will get reviews for 1 banks
[2024-05-06 11:16:29,829] p3726 {/Users/anyarulina/parser/pipeline_review.py:124} INFO - Got info for in 0:00:00.054379 seconds
[2024-05-06 11:16:29,829] p3726 {/Users/anyarulina/parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/parser/pipeline_review.py", line 169, in <module>
    for func in funcs:
TypeError: 'NoneType' object is not iterable
[2024-05-06 11:19:26,686] p3770 {/Users/anyarulina/parser/pipeline_review.py:147} INFO - start pipeline for sberbank at 2024-05-06 11:19:26.686026
[2024-05-06 11:19:26,686] p3770 {/Users/anyarulina/parser/pipeline_review.py:156} INFO - 1 cities in input
[2024-05-06 11:19:26,686] p3770 {/Users/anyarulina/parser/pipeline_review.py:97} INFO - start get info for sberbank at 2024-05-06 11:19:26.686268
[2024-05-06 11:19:26,706] p3770 {/Users/anyarulina/parser/pipeline_review.py:38} INFO - len existing_reviews  4309
[2024-05-06 11:19:26,734] p3770 {/Users/anyarulina/parser/pipeline_review.py:61} INFO - len existing_links  5727
[2024-05-06 11:19:26,742] p3770 {/Users/anyarulina/parser/pipeline_review.py:81} INFO - len not_handled_reviews  1409
[2024-05-06 11:19:26,743] p3770 {/Users/anyarulina/parser/pipeline_review.py:125} INFO - I will get reviews for 1 banks
[2024-05-06 11:19:26,743] p3770 {/Users/anyarulina/parser/pipeline_review.py:130} INFO - Got info for in 0:00:00.056888 seconds
[2024-05-06 11:19:26,743] p3770 {/Users/anyarulina/parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/parser/pipeline_review.py", line 179, in <module>
    for func in funcs:
TypeError: 'NoneType' object is not iterable
[2024-05-06 11:20:10,727] p3808 {/Users/anyarulina/parser/pipeline_review.py:150} INFO - start pipeline for sberbank at 2024-05-06 11:20:10.727420
[2024-05-06 11:20:10,727] p3808 {/Users/anyarulina/parser/pipeline_review.py:159} INFO - 1 cities in input
[2024-05-06 11:20:10,727] p3808 {/Users/anyarulina/parser/pipeline_review.py:100} INFO - start get info for sberbank at 2024-05-06 11:20:10.727628
[2024-05-06 11:20:10,745] p3808 {/Users/anyarulina/parser/pipeline_review.py:38} INFO - len existing_reviews  4309
[2024-05-06 11:20:10,774] p3808 {/Users/anyarulina/parser/pipeline_review.py:61} INFO - len existing_links  5727
[2024-05-06 11:20:10,783] p3808 {/Users/anyarulina/parser/pipeline_review.py:84} INFO - len not_handled_reviews  1409
[2024-05-06 11:20:10,783] p3808 {/Users/anyarulina/parser/pipeline_review.py:128} INFO - I will get reviews for 1 banks
[2024-05-06 11:20:10,783] p3808 {/Users/anyarulina/parser/pipeline_review.py:133} INFO - Got info for in 0:00:00.055878 seconds
[2024-05-06 11:20:10,783] p3808 {/Users/anyarulina/parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/parser/pipeline_review.py", line 182, in <module>
    for func in funcs:
TypeError: 'NoneType' object is not iterable
[2024-05-06 11:33:36,861] p4417 {/Users/anyarulina/parser/pipeline_review.py:142} INFO - start pipeline for sberbank at 2024-05-06 11:33:36.861229
[2024-05-06 11:33:36,861] p4417 {/Users/anyarulina/parser/pipeline_review.py:150} INFO - 631 cities in input
[2024-05-06 11:33:36,861] p4417 {/Users/anyarulina/parser/pipeline_review.py:92} INFO - start get info for sberbank at 2024-05-06 11:33:36.861912
[2024-05-06 11:33:36,878] p4417 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:33:36,927] p4417 {/Users/anyarulina/parser/pipeline_review.py:56} INFO - len existing_links  5727
[2024-05-06 11:33:36,935] p4417 {/Users/anyarulina/parser/pipeline_review.py:76} INFO - len not_handled_reviews  1409
[2024-05-06 11:33:36,939] p4417 {/Users/anyarulina/parser/pipeline_review.py:120} INFO - I will get reviews for 1271 banks
[2024-05-06 11:33:36,939] p4417 {/Users/anyarulina/parser/pipeline_review.py:125} INFO - Got info for in 0:00:00.077420 seconds
[2024-05-06 11:33:36,939] p4417 {/Users/anyarulina/parser/pipeline_review.py:92} INFO - start get info for sberbank at 2024-05-06 11:33:36.939419
[2024-05-06 11:33:36,955] p4417 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:33:36,978] p4417 {/Users/anyarulina/parser/pipeline_review.py:56} INFO - len existing_links  5727
[2024-05-06 11:33:36,986] p4417 {/Users/anyarulina/parser/pipeline_review.py:76} INFO - len not_handled_reviews  1409
[2024-05-06 11:33:36,990] p4417 {/Users/anyarulina/parser/pipeline_review.py:120} INFO - I will get reviews for 1271 banks
[2024-05-06 11:33:36,990] p4417 {/Users/anyarulina/parser/pipeline_review.py:125} INFO - Got info for in 0:00:00.051339 seconds
[2024-05-06 11:33:36,990] p4417 {/Users/anyarulina/parser/pipeline_review.py:179} INFO - Error in None: 'NoneType' object is not callable
[2024-05-06 11:33:36,990] p4417 {/Users/anyarulina/parser/pipeline_review.py:180} INFO - worked 0:00:00.000053 seconds
[2024-05-06 11:33:36,990] p4417 {/Users/anyarulina/parser/pipeline_review.py:179} INFO - Error in None: 'NoneType' object is not callable
[2024-05-06 11:33:36,990] p4417 {/Users/anyarulina/parser/pipeline_review.py:180} INFO - worked 0:00:00.000047 seconds
[2024-05-06 11:33:36,991] p4417 {/Users/anyarulina/parser/pipeline_review.py:185} INFO - I finished at 2024-05-06 11:33:36.991028
[2024-05-06 11:33:36,991] p4417 {/Users/anyarulina/parser/pipeline_review.py:186} INFO - Pipeline worked 0:00:00.129845 seconds
[2024-05-06 11:33:48,290] p4438 {/Users/anyarulina/parser/pipeline_review.py:142} INFO - start pipeline for sberbank at 2024-05-06 11:33:48.290344
[2024-05-06 11:33:48,290] p4438 {/Users/anyarulina/parser/pipeline_review.py:150} INFO - 631 cities in input
[2024-05-06 11:33:48,290] p4438 {/Users/anyarulina/parser/pipeline_review.py:92} INFO - start get info for sberbank at 2024-05-06 11:33:48.290788
[2024-05-06 11:33:48,308] p4438 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:33:48,333] p4438 {/Users/anyarulina/parser/pipeline_review.py:56} INFO - len existing_links  5727
[2024-05-06 11:33:48,342] p4438 {/Users/anyarulina/parser/pipeline_review.py:76} INFO - len not_handled_reviews  1409
[2024-05-06 11:33:48,346] p4438 {/Users/anyarulina/parser/pipeline_review.py:120} INFO - I will get reviews for 1271 banks
[2024-05-06 11:33:48,346] p4438 {/Users/anyarulina/parser/pipeline_review.py:125} INFO - Got info for in 0:00:00.055381 seconds
[2024-05-06 11:33:48,346] p4438 {/Users/anyarulina/parser/pipeline_review.py:92} INFO - start get info for sberbank at 2024-05-06 11:33:48.346254
[2024-05-06 11:33:48,362] p4438 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:33:48,384] p4438 {/Users/anyarulina/parser/pipeline_review.py:56} INFO - len existing_links  5727
[2024-05-06 11:33:48,393] p4438 {/Users/anyarulina/parser/pipeline_review.py:76} INFO - len not_handled_reviews  1409
[2024-05-06 11:33:48,397] p4438 {/Users/anyarulina/parser/pipeline_review.py:120} INFO - I will get reviews for 1271 banks
[2024-05-06 11:33:48,397] p4438 {/Users/anyarulina/parser/pipeline_review.py:125} INFO - Got info for in 0:00:00.051457 seconds
[2024-05-06 11:33:48,397] p4438 {/Users/anyarulina/parser/pipeline_review.py:179} INFO - Error in None: 'NoneType' object is not callable
[2024-05-06 11:33:48,397] p4438 {/Users/anyarulina/parser/pipeline_review.py:180} INFO - worked 0:00:00.000054 seconds
[2024-05-06 11:33:48,397] p4438 {/Users/anyarulina/parser/pipeline_review.py:179} INFO - Error in None: 'NoneType' object is not callable
[2024-05-06 11:33:48,397] p4438 {/Users/anyarulina/parser/pipeline_review.py:180} INFO - worked 0:00:00.000050 seconds
[2024-05-06 11:33:48,398] p4438 {/Users/anyarulina/parser/pipeline_review.py:185} INFO - I finished at 2024-05-06 11:33:48.397997
[2024-05-06 11:33:48,398] p4438 {/Users/anyarulina/parser/pipeline_review.py:186} INFO - Pipeline worked 0:00:00.107698 seconds
[2024-05-06 11:34:20,919] p4481 {/Users/anyarulina/parser/pipeline_review.py:142} INFO - start pipeline for sberbank at 2024-05-06 11:34:20.919133
[2024-05-06 11:34:20,919] p4481 {/Users/anyarulina/parser/pipeline_review.py:150} INFO - 631 cities in input
[2024-05-06 11:34:20,919] p4481 {/Users/anyarulina/parser/pipeline_review.py:92} INFO - start get info for sberbank at 2024-05-06 11:34:20.919532
[2024-05-06 11:34:20,937] p4481 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 11:34:20,967] p4481 {/Users/anyarulina/parser/pipeline_review.py:56} INFO - len existing_links  5727
[2024-05-06 11:34:20,975] p4481 {/Users/anyarulina/parser/pipeline_review.py:76} INFO - len not_handled_reviews  1409
[2024-05-06 11:34:20,979] p4481 {/Users/anyarulina/parser/pipeline_review.py:120} INFO - I will get reviews for 1271 banks
[2024-05-06 11:34:20,979] p4481 {/Users/anyarulina/parser/get_reviews.py:75} INFO - starting get reviews for Россошь city
[2024-05-06 11:34:20,980] p4481 {/Users/anyarulina/parser/get_reviews.py:91} INFO - I will handle 1 banks for city Россошь
[2024-05-06 11:34:20,980] p4481 {/Users/anyarulina/parser/get_reviews.py:92} INFO - links: ['https://yandex.ru/maps/org/sberbank/97017180197']
[2024-05-06 11:34:20,980] p4481 {/Users/anyarulina/parser/get_reviews.py:108} INFO - starting get reviews for id 97017180197
[2024-05-06 11:34:23,777] p4481 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-05-06 11:34:32,890] p4481 {/Users/anyarulina/parser/get_reviews.py:27} INFO - I finish parse.parse 
[2024-05-06 11:34:32,892] p4481 {/Users/anyarulina/parser/get_reviews.py:116} INFO - error local variable 'directory_name' referenced before assignment
[2024-05-06 11:34:32,892] p4481 {/Users/anyarulina/parser/get_reviews.py:117} INFO - 97017180197 not handled
[2024-05-06 11:34:32,893] p4481 {/Users/anyarulina/parser/get_reviews.py:124} INFO - 0 items left
[2024-05-06 11:34:32,893] p4481 {/Users/anyarulina/parser/get_reviews.py:127} INFO - where are no handled banks in city Россошь lentgh of 1: {'Россошь': '97017180197'}
[2024-05-06 11:34:32,893] p4481 {/Users/anyarulina/parser/get_reviews.py:75} INFO - starting get reviews for Омск city
[2024-05-06 11:34:32,893] p4481 {/Users/anyarulina/parser/get_reviews.py:91} INFO - I will handle 1 banks for city Омск
[2024-05-06 11:34:32,893] p4481 {/Users/anyarulina/parser/get_reviews.py:92} INFO - links: ['https://yandex.ru/maps/org/sberbank/90704224041']
[2024-05-06 11:34:32,893] p4481 {/Users/anyarulina/parser/get_reviews.py:108} INFO - starting get reviews for id 90704224041
[2024-05-06 11:34:35,703] p4481 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-05-06 11:34:44,799] p4481 {/Users/anyarulina/parser/get_reviews.py:27} INFO - I finish parse.parse 
[2024-05-06 11:34:44,800] p4481 {/Users/anyarulina/parser/get_reviews.py:116} INFO - error local variable 'directory_name' referenced before assignment
[2024-05-06 11:34:44,800] p4481 {/Users/anyarulina/parser/get_reviews.py:117} INFO - 90704224041 not handled
[2024-05-06 11:34:44,801] p4481 {/Users/anyarulina/parser/get_reviews.py:124} INFO - 0 items left
[2024-05-06 11:34:44,801] p4481 {/Users/anyarulina/parser/get_reviews.py:127} INFO - where are no handled banks in city Омск lentgh of 1: {'Омск': '90704224041'}
[2024-05-06 11:34:44,801] p4481 {/Users/anyarulina/parser/get_reviews.py:75} INFO - starting get reviews for Белово city
[2024-05-06 11:34:44,801] p4481 {/Users/anyarulina/parser/get_reviews.py:91} INFO - I will handle 1 banks for city Белово
[2024-05-06 11:34:44,802] p4481 {/Users/anyarulina/parser/get_reviews.py:92} INFO - links: ['https://yandex.ru/maps/org/sberbank/1005687823']
[2024-05-06 11:34:44,802] p4481 {/Users/anyarulina/parser/get_reviews.py:108} INFO - starting get reviews for id 1005687823
[2024-05-06 11:34:48,342] p4481 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-05-06 11:34:57,436] p4481 {/Users/anyarulina/parser/get_reviews.py:27} INFO - I finish parse.parse 
[2024-05-06 11:34:57,437] p4481 {/Users/anyarulina/parser/get_reviews.py:116} INFO - error local variable 'directory_name' referenced before assignment
[2024-05-06 11:34:57,437] p4481 {/Users/anyarulina/parser/get_reviews.py:117} INFO - 1005687823 not handled
[2024-05-06 11:34:57,438] p4481 {/Users/anyarulina/parser/get_reviews.py:124} INFO - 0 items left
[2024-05-06 11:34:57,438] p4481 {/Users/anyarulina/parser/get_reviews.py:127} INFO - where are no handled banks in city Белово lentgh of 1: {'Белово': '1005687823'}
[2024-05-06 11:34:57,438] p4481 {/Users/anyarulina/parser/get_reviews.py:75} INFO - starting get reviews for Павловский Посад city
[2024-05-06 11:34:57,438] p4481 {/Users/anyarulina/parser/get_reviews.py:91} INFO - I will handle 5 banks for city Павловский Посад
[2024-05-06 11:34:57,438] p4481 {/Users/anyarulina/parser/get_reviews.py:92} INFO - links: ['https://yandex.ru/maps/org/sberbank/1164528854', 'https://yandex.ru/maps/org/sberbank/173059665005', 'https://yandex.ru/maps/org/sberbank/1079586849', 'https://yandex.ru/maps/org/sberbank/1016295355', 'https://yandex.ru/maps/org/sberbank/1029702600']
[2024-05-06 11:34:57,438] p4481 {/Users/anyarulina/parser/get_reviews.py:108} INFO - starting get reviews for id 1164528854
[2024-05-06 11:34:59,921] p4481 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-05-06 11:35:10,040] p4481 {/Users/anyarulina/parser/get_reviews.py:27} INFO - I finish parse.parse 
[2024-05-06 11:35:10,041] p4481 {/Users/anyarulina/parser/get_reviews.py:116} INFO - error local variable 'directory_name' referenced before assignment
[2024-05-06 11:35:10,041] p4481 {/Users/anyarulina/parser/get_reviews.py:117} INFO - 1164528854 not handled
[2024-05-06 11:35:10,042] p4481 {/Users/anyarulina/parser/get_reviews.py:124} INFO - 4 items left
[2024-05-06 11:35:10,042] p4481 {/Users/anyarulina/parser/get_reviews.py:108} INFO - starting get reviews for id 173059665005
[2024-05-06 11:35:12,589] p4481 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-05-06 12:18:30,932] p5764 {/Users/anyarulina/parser/pipeline_review.py:143} INFO - start pipeline for sberbank at 2024-05-06 12:18:30.932957
[2024-05-06 12:18:30,933] p5764 {/Users/anyarulina/parser/pipeline_review.py:154} INFO - 631 cities in input
[2024-05-06 12:18:30,933] p5764 {/Users/anyarulina/parser/pipeline_review.py:92} INFO - start get info for sberbank at 2024-05-06 12:18:30.933654
[2024-05-06 12:18:30,953] p5764 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 12:18:31,006] p5764 {/Users/anyarulina/parser/pipeline_review.py:56} INFO - len existing_links  5727
[2024-05-06 12:18:31,014] p5764 {/Users/anyarulina/parser/pipeline_review.py:76} INFO - len not_handled_reviews  1409
[2024-05-06 12:18:31,016] p5764 {/Users/anyarulina/parser/pipeline_review.py:118} INFO - I will get reviews for 1271 banks
[2024-05-06 12:18:31,016] p5764 {/Users/anyarulina/parser/pipeline_review.py:126} INFO - Got info for in 0:00:00.083064 seconds
[2024-05-06 12:18:31,016] p5764 {/Users/anyarulina/parser/pipeline_review.py:92} INFO - start get info for sberbank at 2024-05-06 12:18:31.016798
[2024-05-06 12:18:31,033] p5764 {/Users/anyarulina/parser/pipeline_review.py:35} INFO - len existing_reviews  4309
[2024-05-06 12:18:31,055] p5764 {/Users/anyarulina/parser/pipeline_review.py:56} INFO - len existing_links  5727
[2024-05-06 12:18:31,063] p5764 {/Users/anyarulina/parser/pipeline_review.py:76} INFO - len not_handled_reviews  1409
[2024-05-06 12:18:31,065] p5764 {/Users/anyarulina/parser/pipeline_review.py:118} INFO - I will get reviews for 1271 banks
[2024-05-06 12:18:31,065] p5764 {/Users/anyarulina/parser/pipeline_review.py:126} INFO - Got info for in 0:00:00.048568 seconds
[2024-05-06 12:18:31,065] p5764 {/Users/anyarulina/parser/pipeline_review.py:183} INFO - Error in None: 'NoneType' object is not callable
[2024-05-06 12:18:31,065] p5764 {/Users/anyarulina/parser/pipeline_review.py:184} INFO - worked 0:00:00.000052 seconds
[2024-05-06 12:18:31,065] p5764 {/Users/anyarulina/parser/pipeline_review.py:183} INFO - Error in None: 'NoneType' object is not callable
[2024-05-06 12:18:31,065] p5764 {/Users/anyarulina/parser/pipeline_review.py:184} INFO - worked 0:00:00.000045 seconds
[2024-05-06 12:18:31,065] p5764 {/Users/anyarulina/parser/pipeline_review.py:189} INFO - I finished at 2024-05-06 12:18:31.065632
[2024-05-06 12:18:31,065] p5764 {/Users/anyarulina/parser/pipeline_review.py:190} INFO - Pipeline worked 0:00:00.132725 seconds
